export const MockData = [
  {
    id: "binance",
    name: "Binance",
    year_established: 2017,
    country: "Cayman Islands",
    description: "",
    url: "https://www.binance.com/",
    image:
      "https://assets.coingecko.com/markets/images/52/small/binance.jpg?1519353250",
    has_trading_incentive: false,
    trust_score: 10,
    trust_score_rank: 1,
    trade_volume_24h_btc: 515369.02242471394,
    trade_volume_24h_btc_normalized: 515369.02242471394,
  },
  {
    id: "okex",
    name: "OKX",
    year_established: 2013,
    country: "Belize",
    description: "",
    url: "https://www.okx.com",
    image:
      "https://assets.coingecko.com/markets/images/96/small/WeChat_Image_20220117220452.png?1642428377",
    has_trading_incentive: false,
    trust_score: 10,
    trust_score_rank: 2,
    trade_volume_24h_btc: 121036.74524605315,
    trade_volume_24h_btc_normalized: 121036.74524605315,
  },
  {
    id: "gdax",
    name: "Coinbase Exchange",
    year_established: 2012,
    country: "United States",
    description: "",
    url: "https://www.coinbase.com",
    image:
      "https://assets.coingecko.com/markets/images/23/small/Coinbase_Coin_Primary.png?1621471875",
    has_trading_incentive: false,
    trust_score: 10,
    trust_score_rank: 3,
    trade_volume_24h_btc: 95255.09351509703,
    trade_volume_24h_btc_normalized: 95255.09351509703,
  },
  {
    id: "crypto_com",
    name: "Crypto.com Exchange",
    year_established: 2019,
    country: "Cayman Islands",
    description:
      "Crypto.com Exchange is the best place to trade crypto, with deep liquidity, low fees and best execution prices, users can trade major cryptocurrencies like Bitcoin, Ethereum, and many more and receive great CRO-powered rewards",
    url: "https://crypto.com/exchange",
    image:
      "https://assets.coingecko.com/markets/images/589/small/Crypto.jpg?1629861084",
    has_trading_incentive: false,
    trust_score: 10,
    trust_score_rank: 4,
    trade_volume_24h_btc: 84090.94475046419,
    trade_volume_24h_btc_normalized: 84090.94475046419,
  },
  {
    id: "mxc",
    name: "MEXC Global",
    year_established: 2018,
    country: null,
    description:
      "Established in April 2018, MEXC Global is one of the world’s leading digital-asset trading platforms. The core team comes from world-class enterprises and financial companies with rich experience in blockchain and financial industries.",
    url: "https://www.mexc.com/",
    image:
      "https://assets.coingecko.com/markets/images/409/small/WeChat_Image_20210622160936.png?1624349423",
    has_trading_incentive: false,
    trust_score: 10,
    trust_score_rank: 5,
    trade_volume_24h_btc: 71851.42448702815,
    trade_volume_24h_btc_normalized: 71851.42448702815,
  },
  {
    id: "bitrue",
    name: "Bitrue",
    year_established: 2018,
    country: "Singapore",
    description: "",
    url: "https://www.bitrue.com/",
    image:
      "https://assets.coingecko.com/markets/images/254/small/Bitrue_Exchange.png?1637142776",
    has_trading_incentive: false,
    trust_score: 10,
    trust_score_rank: 6,
    trade_volume_24h_btc: 68922.39264810938,
    trade_volume_24h_btc_normalized: 68922.39264810938,
  },
  {
    id: "kucoin",
    name: "KuCoin",
    year_established: 2014,
    country: "Seychelles",
    description: "",
    url: "https://www.kucoin.com/",
    image:
      "https://assets.coingecko.com/markets/images/61/small/kucoin.png?1640584259",
    has_trading_incentive: false,
    trust_score: 10,
    trust_score_rank: 7,
    trade_volume_24h_btc: 60457.07873742017,
    trade_volume_24h_btc_normalized: 60457.07873742017,
  },
  {
    id: "gate",
    name: "Gate.io",
    year_established: null,
    country: "Hong Kong",
    description:
      "Gate was established in 2013, and it is the top 10 exchanges in the world in terms of authentic trading volume. It is also the first choice of over 8 million registered customers, covering 130+ countries worldwide, as we are providing the most comprehensive digital asset solutions.",
    url: "https://gate.io/",
    image:
      "https://assets.coingecko.com/markets/images/60/small/gateio.jpg?1519793974",
    has_trading_incentive: false,
    trust_score: 10,
    trust_score_rank: 8,
    trade_volume_24h_btc: 57829.218866582676,
    trade_volume_24h_btc_normalized: 57829.218866582676,
  },
  {
    id: "ftx_spot",
    name: "FTX",
    year_established: 2019,
    country: "Antigua and Barbuda",
    description: "",
    url: "https://ftx.com/",
    image:
      "https://assets.coingecko.com/markets/images/451/small/F.png?1609051590",
    has_trading_incentive: false,
    trust_score: 10,
    trust_score_rank: 9,
    trade_volume_24h_btc: 53068.71111705963,
    trade_volume_24h_btc_normalized: 53068.71111705963,
  },
  {
    id: "bitmart",
    name: "BitMart",
    year_established: 2017,
    country: "Cayman Islands",
    description: "",
    url: "https://www.bitmart.com/en",
    image:
      "https://assets.coingecko.com/markets/images/239/small/Bitmart.png?1628066397",
    has_trading_incentive: false,
    trust_score: 10,
    trust_score_rank: 10,
    trade_volume_24h_btc: 50893.66327117363,
    trade_volume_24h_btc_normalized: 50893.66327117363,
  },
  {
    id: "huobi",
    name: "Huobi Global",
    year_established: 2013,
    country: "Seychelles",
    description: "",
    url: "https://www.huobi.com",
    image:
      "https://assets.coingecko.com/markets/images/25/small/1481589873352_.pic_hd.jpg?1589962155",
    has_trading_incentive: false,
    trust_score: 10,
    trust_score_rank: 11,
    trade_volume_24h_btc: 45534.98445835933,
    trade_volume_24h_btc_normalized: 45534.98445835933,
  },
  {
    id: "kraken",
    name: "Kraken",
    year_established: 2011,
    country: "United States",
    description: "",
    url: "https://r.kraken.com/Q1m9x",
    image:
      "https://assets.coingecko.com/markets/images/29/small/kraken.jpg?1584251255",
    has_trading_incentive: false,
    trust_score: 10,
    trust_score_rank: 12,
    trade_volume_24h_btc: 30889.085529447864,
    trade_volume_24h_btc_normalized: 30889.085529447864,
  },
  {
    id: "bitfinex",
    name: "Bitfinex",
    year_established: 2014,
    country: "British Virgin Islands",
    description: "",
    url: "https://www.bitfinex.com",
    image:
      "https://assets.coingecko.com/markets/images/4/small/BItfinex.png?1615895883",
    has_trading_incentive: false,
    trust_score: 10,
    trust_score_rank: 13,
    trade_volume_24h_btc: 16921.017969797867,
    trade_volume_24h_btc_normalized: 16921.017969797867,
  },
  {
    id: "bybit_spot",
    name: "Bybit (Spot)",
    year_established: 2018,
    country: null,
    description: "",
    url: "https://www.bybit.com",
    image:
      "https://assets.coingecko.com/markets/images/698/small/bybit_spot.png?1629971794",
    has_trading_incentive: false,
    trust_score: 10,
    trust_score_rank: 14,
    trade_volume_24h_btc: 12356.233334741219,
    trade_volume_24h_btc_normalized: 12356.233334741219,
  },
  {
    id: "binance_us",
    name: "Binance US",
    year_established: 2019,
    country: "United States",
    description: "",
    url: "https://www.binance.us/en",
    image:
      "https://assets.coingecko.com/markets/images/469/small/Binance.png?1568875842",
    has_trading_incentive: false,
    trust_score: 10,
    trust_score_rank: 15,
    trade_volume_24h_btc: 10321.267902632919,
    trade_volume_24h_btc_normalized: 10321.267902632919,
  },
  {
    id: "phemex",
    name: "Phemex",
    year_established: 2019,
    country: "Singapore",
    description:
      "Launched in 2019, Phemex is a Singapore-based cryptocurrency and derivatives trading platform led by former Morgan Stanley executives. Serving around 2 million active users in over 200 countries, Phemex supports 37+ trading pairs with up to 100x leverage. It was also the first major exchange to pioneer an optional premium membership model for zero spot trading fees.\r\n\r\n-  Fee Structure: 0.025% maker fee and 0.075% taker fee\r\n-  Up to $100 Welcome Bonus for new users\r\n-  Earn up to 8.5% APY interest income on crypto assets\r\n-  Free academy with 450+ carefully curated articles about crypto & trading\r\n-  Security: Hierarchical Deterministic Cold Wallet System with 2-level human scrutiny offline signatures.",
    url: "https://phemex.com/",
    image:
      "https://assets.coingecko.com/markets/images/564/small/Phemex_logo_4.png?1641357471",
    has_trading_incentive: false,
    trust_score: 10,
    trust_score_rank: 16,
    trade_volume_24h_btc: 10029.219630410724,
    trade_volume_24h_btc_normalized: 10029.219630410724,
  },
  {
    id: "latoken",
    name: "LATOKEN",
    year_established: 2017,
    country: "Cayman Islands",
    description: "",
    url: "https://latoken.com/",
    image:
      "https://assets.coingecko.com/markets/images/124/small/LA_token.png?1605773251",
    has_trading_incentive: false,
    trust_score: 10,
    trust_score_rank: 17,
    trade_volume_24h_btc: 7950.318817334894,
    trade_volume_24h_btc_normalized: 7950.318817334894,
  },
  {
    id: "btse",
    name: "BTSE",
    year_established: 2018,
    country: "British Virgin Islands",
    description:
      "BTSE is your Bitcoin futures exchange to trade with confidence and ease.\r\n\r\nBTSE‘s mission is to make institutional-grade security and stability available to every crypto trader.\r\n\r\nBTSE’s platform is built to facilitate reliable 24/7 trading. It uses an extremely powerful matching engine that eliminates the risk of system overloads, as well as horizontal scaling which enables BTSE to do hot upgrades with zero downtime. BTSE’s insurance fund, strict security protocols, and self-hosted servers allow for the highest level of security for our traders.",
    url: "https://www.btse.com/",
    image:
      "https://assets.coingecko.com/markets/images/464/small/BTSE.jpg?1568012415",
    has_trading_incentive: false,
    trust_score: 10,
    trust_score_rank: 18,
    trade_volume_24h_btc: 5708.365959345705,
    trade_volume_24h_btc_normalized: 5708.365959345705,
  },
  {
    id: "gemini",
    name: "Gemini",
    year_established: 2014,
    country: "United States",
    description: "",
    url: "https://gemini.sjv.io/bZ49k",
    image:
      "https://assets.coingecko.com/markets/images/50/small/gemini.png?1605704107",
    has_trading_incentive: false,
    trust_score: 10,
    trust_score_rank: 19,
    trade_volume_24h_btc: 3766.4989824972713,
    trade_volume_24h_btc_normalized: 3766.4989824972713,
  },
  {
    id: "bittrex",
    name: "Bittrex",
    year_established: 2014,
    country: "United States",
    description: "",
    url: "https://bittrex.com/",
    image:
      "https://assets.coingecko.com/markets/images/10/small/BG-color-250x250_icon.png?1596167574",
    has_trading_incentive: false,
    trust_score: 9,
    trust_score_rank: 20,
    trade_volume_24h_btc: 1870.6883953901647,
    trade_volume_24h_btc_normalized: 1870.6883953901647,
  },
  {
    id: "cryptology",
    name: "Cryptology",
    year_established: 2018,
    country: "Estonia",
    description: "",
    url: "https://cryptology.com/",
    image:
      "https://assets.coingecko.com/markets/images/287/small/cryptology.png?1541390904",
    has_trading_incentive: false,
    trust_score: 10,
    trust_score_rank: 21,
    trade_volume_24h_btc: 1270.5557855562145,
    trade_volume_24h_btc_normalized: 1270.5557855562145,
  },
  {
    id: "digifinex",
    name: "Digifinex",
    year_established: 2018,
    country: "Seychelles",
    description: "",
    url: "https://www.digifinex.com/",
    image:
      "https://assets.coingecko.com/markets/images/225/small/DF_logo.png?1594264355",
    has_trading_incentive: false,
    trust_score: 9,
    trust_score_rank: 22,
    trade_volume_24h_btc: 66257.60455370338,
    trade_volume_24h_btc_normalized: 66257.60455370338,
  },
  {
    id: "bkex",
    name: "BKEX",
    year_established: 2018,
    country: "British Virgin Islands",
    description: "",
    url: "https://www.bkex.com/",
    image:
      "https://assets.coingecko.com/markets/images/293/small/New_BKEX_logo.png?1646724631",
    has_trading_incentive: false,
    trust_score: 9,
    trust_score_rank: 23,
    trade_volume_24h_btc: 47402.04029068163,
    trade_volume_24h_btc_normalized: 47402.04029068163,
  },
  {
    id: "hoo",
    name: "Hoo.com",
    year_established: 2019,
    country: "Cayman Islands",
    description:
      "Hoo.com is a world’s leading blockchain assets service platform, aiming to provide safe and reliable assets management and blockchain services to users worldwide. ",
    url: "https://www.hoo.com",
    image:
      "https://assets.coingecko.com/markets/images/526/small/Hoo_Logo2.jpg?1602237762",
    has_trading_incentive: false,
    trust_score: 9,
    trust_score_rank: 24,
    trade_volume_24h_btc: 28195.580625586543,
    trade_volume_24h_btc_normalized: 28195.580625586543,
  },
  {
    id: "btcturk",
    name: "BtcTurk PRO",
    year_established: 2013,
    country: "Turkey",
    description: "",
    url: "https://pro.btcturk.com/",
    image:
      "https://assets.coingecko.com/markets/images/223/small/BTCTurk-exchange.jpg?1536726120",
    has_trading_incentive: false,
    trust_score: 9,
    trust_score_rank: 25,
    trade_volume_24h_btc: 10528.68733740047,
    trade_volume_24h_btc_normalized: 10528.68733740047,
  },
  {
    id: "bitstamp",
    name: "Bitstamp",
    year_established: 2013,
    country: "United Kingdom",
    description: null,
    url: "https://www.bitstamp.net/",
    image:
      "https://assets.coingecko.com/markets/images/9/small/bitstamp.jpg?1519627979",
    has_trading_incentive: false,
    trust_score: 9,
    trust_score_rank: 26,
    trade_volume_24h_btc: 8167.966701780544,
    trade_volume_24h_btc_normalized: 8167.966701780544,
  },
  {
    id: "bitkub",
    name: "Bitkub",
    year_established: 2018,
    country: "Thailand",
    description: "",
    url: "https://www.bitkub.com",
    image:
      "https://assets.coingecko.com/markets/images/249/small/bitkub.png?1537180687",
    has_trading_incentive: false,
    trust_score: 9,
    trust_score_rank: 27,
    trade_volume_24h_btc: 4492.1784271788865,
    trade_volume_24h_btc_normalized: 4492.1784271788865,
  },
  {
    id: "bitget",
    name: "Bitget",
    year_established: 2018,
    country: "Singapore",
    description: "",
    url: "https://www.bitget.com/",
    image:
      "https://assets.coingecko.com/markets/images/540/small/Bitget_new_logo_2.png?1630049618",
    has_trading_incentive: false,
    trust_score: 9,
    trust_score_rank: 28,
    trade_volume_24h_btc: 4419.597354422741,
    trade_volume_24h_btc_normalized: 4419.597354422741,
  },
  {
    id: "bitbank",
    name: "Bitbank",
    year_established: 2016,
    country: "Japan",
    description: "",
    url: "https://bitbank.cc/",
    image:
      "https://assets.coingecko.com/markets/images/122/small/bitbank.jpg?1521186278",
    has_trading_incentive: false,
    trust_score: 9,
    trust_score_rank: 29,
    trade_volume_24h_btc: 2454.7444196271567,
    trade_volume_24h_btc_normalized: 2454.7444196271567,
  },
  {
    id: "exmo",
    name: "EXMO",
    year_established: 2013,
    country: "United Kingdom",
    description: "",
    url: "https://exmo.com/",
    image:
      "https://assets.coingecko.com/markets/images/59/small/new_logo-1.jpg?1634814504",
    has_trading_incentive: false,
    trust_score: 9,
    trust_score_rank: 30,
    trade_volume_24h_btc: 1912.7686887669577,
    trade_volume_24h_btc_normalized: 1912.7686887669577,
  },
  {
    id: "tokenize",
    name: "Tokenize",
    year_established: 2018,
    country: "Singapore",
    description: "",
    url: "https://tokenize.exchange/",
    image:
      "https://assets.coingecko.com/markets/images/383/small/tokenize-exchange.png?1586138532",
    has_trading_incentive: false,
    trust_score: 9,
    trust_score_rank: 31,
    trade_volume_24h_btc: 972.9633566049907,
    trade_volume_24h_btc_normalized: 972.9633566049907,
  },
  {
    id: "bitso",
    name: "Bitso",
    year_established: 2014,
    country: "Mexico",
    description: "",
    url: "https://bitso.com",
    image:
      "https://assets.coingecko.com/markets/images/8/small/Bitso-icon-dark.png?1581909156",
    has_trading_incentive: false,
    trust_score: 9,
    trust_score_rank: 32,
    trade_volume_24h_btc: 682.924194224855,
    trade_volume_24h_btc_normalized: 682.924194224855,
  },
  {
    id: "upbit",
    name: "Upbit",
    year_established: 2017,
    country: "South Korea",
    description: null,
    url: "https://upbit.com",
    image:
      "https://assets.coingecko.com/markets/images/117/small/upbit.png?1520388800",
    has_trading_incentive: false,
    trust_score: 8,
    trust_score_rank: 33,
    trade_volume_24h_btc: 128914.59989501577,
    trade_volume_24h_btc_normalized: 128914.59989501577,
  },
  {
    id: "xt",
    name: "XT.COM",
    year_established: 2018,
    country: "Seychelles",
    description:
      "Established in Seychelles 2018, and headquartered in Singapore, XT.COM has operation centres in Tokyo, Singapore, Seoul in an effort to globalise our operations. \r\nThe platform has a top-level domain www.xt.com, and currently has more than 3 million registered users, over 300,000 monthly active users, and over 30 million users in the ecosystem.\r\nXT.COM is a comprehensive trading platform that supports 100+ high-quality currencies and 300 trading pairs. It has a rich variety of transactions such as currency transactions, leveraged transactions, OTC transactions, contract transactions, and credit card purchases. We provide users with the safest, most efficient and professional digital asset investment services.",
    url: "https://www.xt.com/",
    image:
      "https://assets.coingecko.com/markets/images/404/small/logo400x400.png?1575881839",
    has_trading_incentive: false,
    trust_score: 8,
    trust_score_rank: 34,
    trade_volume_24h_btc: 66482.56274968272,
    trade_volume_24h_btc_normalized: 66482.56274968272,
  },
  {
    id: "bithumb",
    name: "Bithumb",
    year_established: 2014,
    country: "South Korea",
    description: "",
    url: "https://www.bithumb.com/",
    image:
      "https://assets.coingecko.com/markets/images/6/small/bithumb_BI.png?1573104549",
    has_trading_incentive: false,
    trust_score: 8,
    trust_score_rank: 35,
    trade_volume_24h_btc: 24639.347044190858,
    trade_volume_24h_btc_normalized: 24639.347044190858,
  },
  {
    id: "aax",
    name: "AAX",
    year_established: 2019,
    country: "Seychelles",
    description:
      "AAX is the world’s first cryptocurrency exchange to be powered by LSEG Technology’s Millennium Exchange, the same matching engine at the heart of tier-one capital markets. AAX is a member of London Stock Exchange Group’s global ‘Partner Platform’. Offering OTC, Spot, and Futures trading, quoting more than 50 cryptocurrency pairs and listing 5 perpetual futures contracts for Bitcoin, Ether, Litecoin, Ripple, and EOS, which can be traded with high leverage, AAX provides a secure, deeply liquid, ultra-low latency and fully compliant trading platform. It offers an institutional-grade platform, for everyone. ",
    url: "https://www.aax.com",
    image:
      "https://assets.coingecko.com/markets/images/527/small/aax_app_logo.png?1586779427",
    has_trading_incentive: false,
    trust_score: 8,
    trust_score_rank: 36,
    trade_volume_24h_btc: 24037.61887064145,
    trade_volume_24h_btc_normalized: 24037.61887064145,
  },
  {
    id: "whitebit",
    name: "WhiteBIT",
    year_established: 2018,
    country: "Estonia",
    description: "",
    url: "https://whitebit.com",
    image:
      "https://assets.coingecko.com/markets/images/418/small/wb_3_avatar-02.png?1611212424",
    has_trading_incentive: false,
    trust_score: 8,
    trust_score_rank: 37,
    trade_volume_24h_btc: 22639.420810746764,
    trade_volume_24h_btc_normalized: 22639.420810746764,
  },
  {
    id: "coinflex",
    name: "CoinFLEX",
    year_established: 2019,
    country: "Seychelles",
    description: "",
    url: "https://coinflex.com/",
    image:
      "https://assets.coingecko.com/markets/images/446/small/CoinFlex.png?1579227306",
    has_trading_incentive: false,
    trust_score: 8,
    trust_score_rank: 38,
    trade_volume_24h_btc: 35657.48079258771,
    trade_volume_24h_btc_normalized: 13652.193949646868,
  },
  {
    id: "coinsbit",
    name: "Coinsbit",
    year_established: null,
    country: "Estonia",
    description: "",
    url: "https://coinsbit.io/",
    image:
      "https://assets.coingecko.com/markets/images/267/small/Coinsbit.png?1605153697",
    has_trading_incentive: false,
    trust_score: 8,
    trust_score_rank: 39,
    trade_volume_24h_btc: 11908.596042740233,
    trade_volume_24h_btc_normalized: 11908.596042740233,
  },
  {
    id: "hotbit",
    name: "Hotbit",
    year_established: null,
    country: "Estonia",
    description:
      "Founded in 2018 and holding Estonian MTR licence, American MSB licence, an Australian AUSTRAC licence and a Canadian MSB licence，HotBit cryptocurrency exchange is known as a cryptocurrency trading platofrm that continues to develop and integrate various forms of businesses such as spot trading, financial derivatives, cryptocurrency investment and DAPP into one platform. Currently, Hotbit’s businesses covers more than 210 countries and areas. Based on its globalized and unified strategies, HotBit continues to focus on world's emerging markets such as Russia, Turkey and southeastern Asia markets, and was ranked one of the top 3 most welcomed exchanges by Russian media in 2019.",
    url: "https://www.hotbit.io/",
    image:
      "https://assets.coingecko.com/markets/images/201/small/hotbit.jpg?1531043195",
    has_trading_incentive: false,
    trust_score: 8,
    trust_score_rank: 40,
    trade_volume_24h_btc: 8051.929962621091,
    trade_volume_24h_btc_normalized: 8051.929962621091,
  },
  {
    id: "goku",
    name: "GokuMarket",
    year_established: 2019,
    country: "Hong Kong",
    description:
      "Launched on 20/11/2019, GokuMarket is a centralized exchange and crypto utility provider. It supports crypto trading/crypto purchase with card/cash-out with debit card/staking/autobots/e-commerce/freelancers/travel bookings/IEOs, all accessible on web & mobile Android/iOS App.",
    url: "https://gokumarket.com",
    image:
      "https://assets.coingecko.com/markets/images/590/small/GokuMarket-Logo-200-200-1.png?1601890565",
    has_trading_incentive: false,
    trust_score: 8,
    trust_score_rank: 41,
    trade_volume_24h_btc: 6074.371847765077,
    trade_volume_24h_btc_normalized: 6074.371847765077,
  },
  {
    id: "bitflyer",
    name: "bitFlyer",
    year_established: 2014,
    country: "Japan",
    description: "",
    url: "https://bitflyereuropesa.pxf.io/c/2223866/858437/11990",
    image:
      "https://assets.coingecko.com/markets/images/5/small/bitFlyer-logo.png?1643256033",
    has_trading_incentive: false,
    trust_score: 8,
    trust_score_rank: 42,
    trade_volume_24h_btc: 5542.896754665675,
    trade_volume_24h_btc_normalized: 5542.896754665675,
  },
  {
    id: "dextrade",
    name: "Dex-Trade",
    year_established: 2019,
    country: "Belize",
    description:
      "Dex-Trade is a centralized cryptocurrency exchange founded in 2017 and registered in Belize. This is a modern space for safe and comfortable trading with minimal commissions.\r\n\r\nDex-Trade is a universal exchange for both beginners and professional traders. The minimum spread and high liquidity in order books allow you to trade efficiently with orders of any volume.\r\nAlong with global opportunities, the exchange also provides a demo trading mode for risk-free testing of your trading strategies. Our dedicated support team is online 24/7 to assist you with any questions.\r\n\r\nYou can learn more about Dex-Trade on the website.\r\nhttps://dex-trade.com/info/about\r\n\r\nIf you are looking for listing and promotion options with Dex-Trade please visit our listing page and a personal manager will help you to utilize our proven tools and intelligent market-making system to engage with the vast exchange community in the best possible way. https://dex-trade.com/listing",
    url: "https://dex-trade.com/",
    image:
      "https://assets.coingecko.com/markets/images/380/small/Dex-Trade_logo_new.png?1599629803",
    has_trading_incentive: false,
    trust_score: 8,
    trust_score_rank: 43,
    trade_volume_24h_btc: 5502.5168087685815,
    trade_volume_24h_btc_normalized: 5502.5168087685815,
  },
  {
    id: "ftx_us",
    name: "FTX.US",
    year_established: 2020,
    country: "United States",
    description: "",
    url: "https://ftx.us/",
    image:
      "https://assets.coingecko.com/markets/images/532/small/FTX-US.jpg?1609051756",
    has_trading_incentive: false,
    trust_score: 8,
    trust_score_rank: 44,
    trade_volume_24h_btc: 4903.920711436685,
    trade_volume_24h_btc_normalized: 4903.920711436685,
  },
  {
    id: "bitmax",
    name: "AscendEX (BitMax)",
    year_established: 2018,
    country: "Singapore",
    description:
      "AscendEX (formerly BitMax) is a leading global digital asset financial platform founded by a group of Wall Street quantitative trading veterans in 2018, building on core value of “Efficiency, Resilience and Transparency.” \r\n \r\nDriven by its continuous innovative product development and early-mover advantage in strategic alignment with the leading projects from DeFi ecosystem, AscendEX offers trading services across over 200 trading pairs across cash, margin, and futures products, in particular margin trading of over 50 tokens in cross-asset collateral mode and futures trading in both cross-asset and isolated margin modes.",
    url: "https://ascendex.com/en/global-digital-asset-platform",
    image:
      "https://assets.coingecko.com/markets/images/277/small/ascendex.jpg?1648024546",
    has_trading_incentive: false,
    trust_score: 8,
    trust_score_rank: 45,
    trade_volume_24h_btc: 2961.023471148923,
    trade_volume_24h_btc_normalized: 2961.023471148923,
  },
  {
    id: "coinex",
    name: "CoinEx",
    year_established: 2017,
    country: "United Kingdom",
    description: "",
    url: "https://www.coinex.com/",
    image:
      "https://assets.coingecko.com/markets/images/135/small/coinex.jpg?1527737297",
    has_trading_incentive: false,
    trust_score: 8,
    trust_score_rank: 46,
    trade_volume_24h_btc: 2275.397393884848,
    trade_volume_24h_btc_normalized: 2275.397393884848,
  },
  {
    id: "kickex",
    name: "KickEX",
    year_established: 2020,
    country: "Estonia",
    description:
      "KickEX is a centralized exchange that was launched in June 2020 and was developed with the goal of offering bank-grade security, architecture, and quality standards. KiсkEX supports buying cryptocurrencies with fiat via Visa and Mastercard bank cards, with fiat withdrawals coming in Q4 2020. In this way, KickEX aims to allow users to buy digital assets easily, store them safely on the secure mosiac cold storage systems, trade, exchange, and withdraw crypto or fiat straight to a bank card or to a bank account.",
    url: "https://kickex.com/en",
    image:
      "https://assets.coingecko.com/markets/images/635/small/_JidUguP_400x400.jpg?1615263901",
    has_trading_incentive: false,
    trust_score: 8,
    trust_score_rank: 47,
    trade_volume_24h_btc: 1443.3898987927068,
    trade_volume_24h_btc_normalized: 1443.3898987927068,
  },
  {
    id: "poloniex",
    name: "Poloniex",
    year_established: 2014,
    country: "Seychelles",
    description: "",
    url: "https://poloniex.com/",
    image:
      "https://assets.coingecko.com/markets/images/37/small/poloniex-400.png?1632479317",
    has_trading_incentive: false,
    trust_score: 8,
    trust_score_rank: 48,
    trade_volume_24h_btc: 1324.952867515107,
    trade_volume_24h_btc_normalized: 1324.952867515107,
  },
  {
    id: "coinstore",
    name: "Coinstore",
    year_established: 2021,
    country: "Singapore",
    description: "",
    url: "https://www.coinstore.com/#/",
    image:
      "https://assets.coingecko.com/markets/images/747/small/coinstore.jpeg?1639530357",
    has_trading_incentive: false,
    trust_score: 8,
    trust_score_rank: 49,
    trade_volume_24h_btc: 1076.8994225013978,
    trade_volume_24h_btc_normalized: 1076.8994225013978,
  },
  {
    id: "etorox",
    name: "eToroX",
    year_established: 2019,
    country: "Gibraltar",
    description:
      "eToroX is eToro’s professional crypto exchange. Designed exclusively for the corporate and institutional-grade crypto trading community, the eToroX exchange is a highly effective, trusted and secure crypto trading solution, which is licensed and regulated by the Gibraltar Financial Services Commission under the Investments and Financial Fiduciary Services Act (licence number FSC1333B). eToroX currently has more than 30 digital assets, including 17 tokenized fiat and commodity stablecoins, and more than 100 trading pairs.",
    url: "https://www.etorox.com/",
    image:
      "https://assets.coingecko.com/markets/images/503/small/eToroX_Logo_400x400.jpg?1580209571",
    has_trading_incentive: false,
    trust_score: 8,
    trust_score_rank: 50,
    trade_volume_24h_btc: 1038.5721896840525,
    trade_volume_24h_btc_normalized: 1038.5721896840525,
  },
  {
    id: "indodax",
    name: "Indodax",
    year_established: 2014,
    country: "Indonesia",
    description: "",
    url: "https://indodax.com",
    image:
      "https://assets.coingecko.com/markets/images/3/small/logogram-Indodax-new-_JPG_format.jpg?1580974378",
    has_trading_incentive: false,
    trust_score: 8,
    trust_score_rank: 51,
    trade_volume_24h_btc: 1021.0687493814393,
    trade_volume_24h_btc_normalized: 1021.0687493814393,
  },
  {
    id: "nominex",
    name: "Nominex",
    year_established: 2019,
    country: "Seychelles",
    description:
      "New trading platform for convenient trading experience with low fees and numerous instruments. \r\n\r\nAbsolutely unique affiliate program that allows to earn from an infinite number of referral levels, compared to 2-3 levels at all other exchanges. \r\n\r\nA unique model for the free 2 phases distribution of the native NMX token.\r\n\r\nAdvanced Trading Instruments – using Stop, Stop Limit, Trailing Stop, Scaled and other types of orders brings some kind of trading automation without the need to develop a trading bot, which allows to easily get more profit while trading.",
    url: "https://www.nominex.io",
    image:
      "https://assets.coingecko.com/markets/images/530/small/logo-200x200.png?1587543672",
    has_trading_incentive: false,
    trust_score: 8,
    trust_score_rank: 52,
    trade_volume_24h_btc: 936.2751558194301,
    trade_volume_24h_btc_normalized: 936.2751558194301,
  },
  {
    id: "luno",
    name: "Luno",
    year_established: 2013,
    country: "Singapore",
    description: "",
    url: "https://www.luno.com",
    image:
      "https://assets.coingecko.com/markets/images/33/small/luno.jpg?1519996997",
    has_trading_incentive: false,
    trust_score: 8,
    trust_score_rank: 53,
    trade_volume_24h_btc: 840.4180753860253,
    trade_volume_24h_btc_normalized: 840.4180753860253,
  },
  {
    id: "emirex",
    name: "Emirex",
    year_established: 2019,
    country: "Estonia",
    description:
      "Launched on 10/09/2019, Emirex is a centralized exchange located at 405, Al Saaha Offices C, Dubai, UAE. It supports USD, EUR, AED fiat pairs/OTC/IEOs",
    url: "https://www.emirex.com/",
    image:
      "https://assets.coingecko.com/markets/images/592/small/Emirex.png?1602067691",
    has_trading_incentive: false,
    trust_score: 8,
    trust_score_rank: 54,
    trade_volume_24h_btc: 794.430125825354,
    trade_volume_24h_btc_normalized: 794.430125825354,
  },
  {
    id: "max_maicoin",
    name: "Max Maicoin",
    year_established: null,
    country: "Taiwan",
    description: "",
    url: "https://max.maicoin.com",
    image:
      "https://assets.coingecko.com/markets/images/218/small/max.jpg?1533888641",
    has_trading_incentive: false,
    trust_score: 8,
    trust_score_rank: 55,
    trade_volume_24h_btc: 637.9006333776415,
    trade_volume_24h_btc_normalized: 637.9006333776415,
  },
  {
    id: "okcoin",
    name: "Okcoin",
    year_established: 2013,
    country: "United States",
    description:
      "About OKCoin:\r\nOKCoin is one of the largest and most trusted fiat-to-crypto trading platforms in the world. Founded in 2013, OKCoin offers advanced features for crypto beginners and high-volume traders alike, enabling users in 184 countries worldwide to exchange US dollars and the euro for Bitcoin, Tethers, USDK, Bitcoin Cash, Ethereum, Ethereum Classic, Decred, EOS, Litecoin, XRP, Cardano, 0x, Stellar, Zcash, TRX, and other digital assets. As a registered Money Services Business (MSB) with the Financial Crimes Enforcement Network (FinCEN) and a Virtual Financial Asset Act (VFAA) exchange with a transitory provision permissioned by the Malta Financial Services Authority, OKCoin is on a mission to make digital assets accessible to the world while complying with the highest of regulatory standards. For more information, visit www.okcoin.com. ",
    url: "https://www.okcoin.com/",
    image:
      "https://assets.coingecko.com/markets/images/415/small/okcoin_Logomark_SatoshiBlack.png?1619574335",
    has_trading_incentive: false,
    trust_score: 8,
    trust_score_rank: 56,
    trade_volume_24h_btc: 516.0296652258413,
    trade_volume_24h_btc_normalized: 516.0296652258413,
  },
  {
    id: "independent_reserve",
    name: "Independent Reserve",
    year_established: 2013,
    country: "Australia",
    description: "",
    url: "https://www.independentreserve.com/",
    image:
      "https://assets.coingecko.com/markets/images/389/small/x_V5Jquo_400x400.png?1556071437",
    has_trading_incentive: false,
    trust_score: 8,
    trust_score_rank: 57,
    trade_volume_24h_btc: 277.5189223886114,
    trade_volume_24h_btc_normalized: 277.5189223886114,
  },
  {
    id: "b2bx",
    name: "B2BX",
    year_established: 2017,
    country: "Estonia",
    description: "",
    url: "https://www.b2bx.exchange/",
    image:
      "https://assets.coingecko.com/markets/images/226/small/b2bx.jpg?1534242273",
    has_trading_incentive: false,
    trust_score: 8,
    trust_score_rank: 58,
    trade_volume_24h_btc: 452.59118379138266,
    trade_volume_24h_btc_normalized: 260.4079328358999,
  },
  {
    id: "coin_metro",
    name: "Coinmetro",
    year_established: 2018,
    country: "Estonia",
    description: "",
    url: "https://coinmetro.com/",
    image:
      "https://assets.coingecko.com/markets/images/386/small/Coinmetro_Exchange_Logo_%282%29.png?1646280101",
    has_trading_incentive: false,
    trust_score: 8,
    trust_score_rank: 59,
    trade_volume_24h_btc: 65.85541083174907,
    trade_volume_24h_btc_normalized: 65.85541083174907,
  },
  {
    id: "kuna",
    name: "Kuna Exchange",
    year_established: null,
    country: "United Kingdom",
    description: "",
    url: "https://kuna.io/",
    image:
      "https://assets.coingecko.com/markets/images/97/small/kuna_exchange.png?1545126178",
    has_trading_incentive: false,
    trust_score: 8,
    trust_score_rank: 60,
    trade_volume_24h_btc: 51.251664878429274,
    trade_volume_24h_btc_normalized: 51.251664878429274,
  },
  {
    id: "p2pb2b",
    name: "P2PB2B",
    year_established: 2018,
    country: "Estonia",
    description:
      "P2PB2B Exchange is not just a cryptocurrency exchange platform but also a trusted partner for crypto projects. Our Crypto Startup Partner initiative provides trading consulting and helps our clients develop their community, support liquidity, create growth strategies.\r\n\r\nP2PB2B runs token sales of the promising crypto assets, enabling users to easily invest in new currencies. There are also available services for users such as the earning deposit program, regular gamification events - airdrop, trading competitions, referral program games.\r\n\r\nThe platform is compliant with OWASP TOP 10 security requirements and is recognized as the world's 12th most Trust Core secure crypto exchanges according to CER rating.\r\n\r\nP2PB2B utilizes the high processing speed with the ability to handle up to 10,000 trades per second, scaling to 1,000,000 TCP connections. Our KYC identity verification process leverages AI-powered technology which speeds up the authentication process. 24/7 live support is an essential advantage for users.",
    url: "https://p2pb2b.com/",
    image:
      "https://assets.coingecko.com/markets/images/251/small/p2pb2b.jpg?1536307348",
    has_trading_incentive: false,
    trust_score: 7,
    trust_score_rank: 61,
    trade_volume_24h_btc: 37283.549355962794,
    trade_volume_24h_btc_normalized: 37283.549355962794,
  },
  {
    id: "zb",
    name: "ZB",
    year_established: 2017,
    country: "China",
    description: "",
    url: "https://www.zb.land/en/",
    image:
      "https://assets.coingecko.com/markets/images/115/small/zb.jpg?1519996151",
    has_trading_incentive: false,
    trust_score: 7,
    trust_score_rank: 62,
    trade_volume_24h_btc: 39770.66584064507,
    trade_volume_24h_btc_normalized: 34595.9174988514,
  },
  {
    id: "bitforex",
    name: "Bitforex",
    year_established: 2018,
    country: "Seychelles",
    description: "",
    url: "https://www.bitforex.com/",
    image:
      "https://assets.coingecko.com/markets/images/214/small/BitForex-Logo.png?1573808227",
    has_trading_incentive: false,
    trust_score: 7,
    trust_score_rank: 63,
    trade_volume_24h_btc: 23812.481150434436,
    trade_volume_24h_btc_normalized: 23812.481150434436,
  },
  {
    id: "bigone",
    name: "BigONE",
    year_established: 2017,
    country: "Seychelles",
    description: "",
    url: "https://bigone.com",
    image:
      "https://assets.coingecko.com/markets/images/100/small/qcFFufEY_400x400.jpg?1561103345",
    has_trading_incentive: false,
    trust_score: 7,
    trust_score_rank: 64,
    trade_volume_24h_btc: 23200.46961279598,
    trade_volume_24h_btc_normalized: 23200.46961279598,
  },
  {
    id: "lbank",
    name: "LBank",
    year_established: 2017,
    country: "China",
    description:
      "Founded in October 2016, LBank is a centralized digital asset trading platform for international users. It aims to provide professional asset management solutions. At present, LBank offers hundreds of digital currency pairs. LBank also claims to have one of the highest staking rewards on any exchange.\r\n\r\nLBank's claims that its core team comes from the traditional financial industry, IT, and top 500 universities. The team aims to build the most professional integrated service platform for digital assets while ensuring security.",
    url: "https://www.lbank.info/",
    image:
      "https://assets.coingecko.com/markets/images/118/small/LBank%E5%9C%86%E6%A0%87.png?1572923264",
    has_trading_incentive: false,
    trust_score: 7,
    trust_score_rank: 65,
    trade_volume_24h_btc: 20528.598593733233,
    trade_volume_24h_btc_normalized: 20528.598593733233,
  },
  {
    id: "currency",
    name: "Currency.com",
    year_established: 2019,
    country: "Gibraltar",
    description:
      'Currency.com is the world’s first regulated tokenised securities exchange enabling anyone with crypto and fiat to trade financial assets from the world’s biggest companies with up to 500x leverage. \r\n \r\nCurrency.com enables crypto holders to make the most of your investment by offering access to more than 1300 tokenised securities of the most traded global financial assets – all without putting your crypto holdings under price pressure or converting to fiat" to the following one "Currency.com enables crypto holders to make the most of your investment by offering access to more than 2000+ tokenised securities of the most traded global financial assets – all without putting your crypto holdings under price pressure or converting to fiat\r\n \r\nWith Currency.com you can:\r\n- Do more with less with up to 500x leverage (or buy and sell assets of your choice);\r\n- Manage your risk with sell at loss, guaranteed sell at loss, take profit orders;\r\n- Elevate your trading strategy with access to over 75 technical indicators;\r\n- Fund your account and withdraw via card, bank transfer or crypto wallet;\r\n- Step ahead of the pack with instant price alerts;\r\n- Never lose more than you put in with negative balance protection;\r\n- Trade confidently with a regulated platform and dedicated human support;\r\n- See where you stand with personalised trading reports.\r\n \r\nCurrency.com offers you a new generation financial app for both crypto and fiat. The free mobile platform is designed to buy and sell cryptos with fiat money, store holdings in a secure place and make cross-crypto exchanges. Competitive quotes are coupled with trusted regulatory standards to give users the best possible financial experience.\r\n \r\nCurrency.com – an exchange where crypto meets Wall St.',
    url: "https://currency.com/",
    image:
      "https://assets.coingecko.com/markets/images/512/small/Currency.com_200x200.png?1582086630",
    has_trading_incentive: false,
    trust_score: 7,
    trust_score_rank: 66,
    trade_volume_24h_btc: 13403.83555174927,
    trade_volume_24h_btc_normalized: 13403.83555174927,
  },
  {
    id: "bibox",
    name: "Bibox",
    year_established: 2017,
    country: "China",
    description: "",
    url: "https://www.bibox.com/",
    image:
      "https://assets.coingecko.com/markets/images/114/small/bibox.jpg?1520752603",
    has_trading_incentive: false,
    trust_score: 7,
    trust_score_rank: 67,
    trade_volume_24h_btc: 13178.634976359202,
    trade_volume_24h_btc_normalized: 13178.634976359202,
  },
  {
    id: "paribu",
    name: "Paribu",
    year_established: null,
    country: "Turkey",
    description: null,
    url: "https://www.paribu.com/",
    image:
      "https://assets.coingecko.com/markets/images/136/small/paribu.jpg?1527734779",
    has_trading_incentive: null,
    trust_score: 7,
    trust_score_rank: 68,
    trade_volume_24h_btc: 7371.124251198602,
    trade_volume_24h_btc_normalized: 7371.124251198602,
  },
  {
    id: "cointiger",
    name: "CoinTiger",
    year_established: 2017,
    country: "Singapore",
    description: "",
    url: "https://www.cointiger.com/",
    image:
      "https://assets.coingecko.com/markets/images/204/small/cointiger.png?1588935091",
    has_trading_incentive: false,
    trust_score: 7,
    trust_score_rank: 69,
    trade_volume_24h_btc: 6876.042156924592,
    trade_volume_24h_btc_normalized: 6876.042156924592,
  },
  {
    id: "coinone",
    name: "Coinone",
    year_established: 2016,
    country: "South Korea",
    description: "",
    url: "https://coinone.co.kr/",
    image:
      "https://assets.coingecko.com/markets/images/20/small/coinone_circle_500x500.png?1606460853",
    has_trading_incentive: false,
    trust_score: 7,
    trust_score_rank: 70,
    trade_volume_24h_btc: 3618.3167936193945,
    trade_volume_24h_btc_normalized: 3618.3167936193945,
  },
  {
    id: "exmarkets",
    name: "ExMarkets",
    year_established: 2018,
    country: "British Virgin Islands",
    description: "",
    url: "https://exmarkets.com",
    image:
      "https://assets.coingecko.com/markets/images/363/small/42200149_2115011248752220_3911078373144657920_n.jpg?1551247813",
    has_trading_incentive: false,
    trust_score: 7,
    trust_score_rank: 71,
    trade_volume_24h_btc: 3520.0661080034392,
    trade_volume_24h_btc_normalized: 3520.0661080034392,
  },
  {
    id: "wazirx",
    name: "WazirX",
    year_established: 2018,
    country: "India",
    description: "",
    url: "https://wazirx.com/",
    image:
      "https://assets.coingecko.com/markets/images/274/small/wazirx.jpg?1540450020",
    has_trading_incentive: false,
    trust_score: 7,
    trust_score_rank: 72,
    trade_volume_24h_btc: 3157.582746656918,
    trade_volume_24h_btc_normalized: 3157.582746656918,
  },
  {
    id: "coincheck",
    name: "Coincheck",
    year_established: 2014,
    country: "Japan",
    description: null,
    url: "https://coincheck.com/",
    image:
      "https://assets.coingecko.com/markets/images/18/small/Coincheck.jpg?1519703836",
    has_trading_incentive: null,
    trust_score: 7,
    trust_score_rank: 73,
    trade_volume_24h_btc: 2706.6978252821914,
    trade_volume_24h_btc_normalized: 2706.6978252821914,
  },
  {
    id: "decoin",
    name: "Decoin",
    year_established: 2017,
    country: "Estonia",
    description:
      "Founded in 2017, Decoin is an exchange designed by the crypto community for the crypto community. Our mission is to provide a maximum-security exchange that has an easy-to-use interface for novice users, and advanced trading features for industry veterans. Decoin’s ecosystem also includes a profit-sharing coin called DTEP, which is powered by an independent blockchain using a PoS consensus algorithm. We are led by an experienced team of fintech experts, financial professionals, and experienced traders.",
    url: "https://www.decoin.io",
    image:
      "https://assets.coingecko.com/markets/images/479/small/decoin.jpg?1578456566",
    has_trading_incentive: false,
    trust_score: 7,
    trust_score_rank: 74,
    trade_volume_24h_btc: 2009.780703147214,
    trade_volume_24h_btc_normalized: 2009.780703147214,
  },
  {
    id: "stormgain",
    name: "Stormgain",
    year_established: null,
    country: null,
    description:
      "StormGain is a crypto trading platform for everyone. It’s a convenient solution for those who want to profit from either the growth or decline of the cryptocurrency market and from long-term investments in crypto assets.\r\nAvailable on any device, StormGain allows you to start trading the most popular and most capitalised coins with a multiplier of up to 200x, or you can just buy and hodl crypto.",
    url: "https://stormgain.com/?utm_id=1DSE&utm_source=coingecko_storm&utm_medium=media&utm_campaign=listing&utm_country=en",
    image:
      "https://assets.coingecko.com/markets/images/608/small/CpDGk9Hn_400x400.png?1607582976",
    has_trading_incentive: false,
    trust_score: 7,
    trust_score_rank: 75,
    trade_volume_24h_btc: 1311.280495543236,
    trade_volume_24h_btc_normalized: 1311.280495543236,
  },
  {
    id: "coindeal",
    name: "Coindeal",
    year_established: 2018,
    country: "Malta",
    description:
      "CoinDeal is one of the fastest-growing crypto-fiat exchanges in Europe.\r\n\r\nThe company is located in Malta and is subject to Maltese regulations.\r\nOn 25 November this year, a managerial delegation from CoinDeal went to Malta to meet with the Malta Financial Services Authority (MFSA). This is the next stage that leads the exchange to receive the Maltese VFA license. \r\nRead more HERE. CoinDeal meets the requirements of the VFA Class 4 and all its activities are legal. \r\nIts credibility is confirmed by its entry into the American market, which involved meeting a number of legal requirements. Thanks to Coindeal's compliance with all these requirements, it is now available in 13 states. You can read more HERE.\r\n\r\nWHAT DO WE OFFER\r\nWe are one of the largest exchanges in Europe with more than 40 cryptocurrencies pairs in our offer, including the most popular ones such as Ethereum, Bitcoin or Litecoin and FIAT currencies: Euro (EUR), Dollar (USD), British pound (GBP), Polish zloty (PLN), Swiss franc (CHF)\r\nWe always want to provide our users with the opportunity to actively participate in the development of CoinDeal, so by voting for new cryptocurrency users can decide which of them will be added to the exchange. \r\n\r\nCDL TOKEN\r\nCoinDeal exchange created its own Token to give it for free to its users. It was the first Token in the world to be distributed free of charge to so many people. It was as many as 87 549 users of the Coindeal exchange! 45 000 000 000 Tokens were distributed, which is 90% of all created Tokens. When the market opened for CDL, which took place on November 12, 2019, the value of all Tokens was 1 129 382 USD (382 BTC)! In the beginning, CDL is available together with BTC. The pairs planned for the near future are CDL/EUR and CDL/USDT. Additionally, the exchange offers many benefits from having CDL Tokens on your account. Among other things, it is a 0% fee and you can read about it on the official Token website.\r\n\r\nSECURITY\r\nOur platform has the highest SSL standard security integrated with Cloudflare functionality. User accounts are protected by a multi-level 2FA verification. For the withdrawal of funds, it is necessary to have an email confirmation, which is also required when using the platform with new IP addresses. 90% of user funds are stored on cold wallets protected by Multisignature.\r\n\r\nOUR TEAM\r\nKajetan Maćkowiak and Adam Bicz  are the main managers of CoinDeal.\r\n\r\nAdam has built his long-standing experience in the IT and blockchain sector in the international arena. As the chief programmer at CoinDeal, he is the leader of the team responsible for the development and security of the exchange. Adam operates not only within the BlockchainHouse brand but is also the creator of the BuyCoinNow and Paycoiner payment gateway. \r\n\r\nKajetan has been involved in co-creating blockchain technology projects for years. His professional experience allows him to effectively develop his business and manage his marketing activities. He created an international umbrella brand, which is BlockchainHouse. He is a co-creator of global brands such as Paycoiner and BuyCoinNow. \r\n",
    url: "https://coindeal.com/",
    image:
      "https://assets.coingecko.com/markets/images/313/small/2ZP5JaIL_400x400.jpg?1541109266",
    has_trading_incentive: false,
    trust_score: 7,
    trust_score_rank: 76,
    trade_volume_24h_btc: 1057.9405797667314,
    trade_volume_24h_btc_normalized: 1057.9405797667314,
  },
  {
    id: "blockchain_com",
    name: "Blockchain.com",
    year_established: 2012,
    country: "United Kingdom",
    description: "",
    url: "https://www.blockchain.com/",
    image:
      "https://assets.coingecko.com/markets/images/613/small/unnamedddd.png?1610503741",
    has_trading_incentive: false,
    trust_score: 7,
    trust_score_rank: 77,
    trade_volume_24h_btc: 710.2974447152747,
    trade_volume_24h_btc_normalized: 710.2974447152747,
  },
  {
    id: "maiar",
    name: "Maiar",
    year_established: 2021,
    country: null,
    description:
      "The Maiar Decentralized Exchange (DEX) is the Automated Market Maker (AMM), rearchitecting some of the key elements to build a product that can leverage the entire \r\nperformance of the Elrond architecture, to offer global, near-instant, inexpensive transactions among an expanding suite of assets.\r\n\r\nThe essence of current versions of automated market makers is best expressed through the constant product equation: x * y = k\r\n\r\nBased on it, if a swap pool owns some units of token x and some units of token y, it prices trades so that the quantities of x and y resulting after the trade, when multiplied, are equal to a fixed constant, k.\r\n\r\nBut current AMM performance could be significantly improved by rebuilding them on \r\nvastly more scalable architectures.\r\n\r\nBy reimagining an automated market maker on top of a highly scalable architecture that is high bandwidth, low latency, and inexpensive, the performance of the swap processes can be drastically improved. With significantly better performance, the scope of AMMs can be rapidly expanded, giving birth to new mark",
    url: "https://maiar.exchange/",
    image:
      "https://assets.coingecko.com/markets/images/741/small/maiar-dex.png?1638433160",
    has_trading_incentive: false,
    trust_score: 7,
    trust_score_rank: 78,
    trade_volume_24h_btc: 518.8640216475009,
    trade_volume_24h_btc_normalized: 518.8640216475009,
  },
  {
    id: "cex",
    name: "CEX.IO",
    year_established: 2013,
    country: "United Kingdom",
    description: "",
    url: "https://cex.io/",
    image:
      "https://assets.coingecko.com/markets/images/56/small/main-icon.png?1617267530",
    has_trading_incentive: false,
    trust_score: 7,
    trust_score_rank: 79,
    trade_volume_24h_btc: 468.7057889884005,
    trade_volume_24h_btc_normalized: 468.7057889884005,
  },
  {
    id: "bitopro",
    name: "BitoPro",
    year_established: 2018,
    country: "Taiwan",
    description: "",
    url: "https://www.bitopro.com/",
    image:
      "https://assets.coingecko.com/markets/images/358/small/bitopro_coingecko_250x250_%281%29.png?1575884378",
    has_trading_incentive: false,
    trust_score: 7,
    trust_score_rank: 80,
    trade_volume_24h_btc: 330.00229062521026,
    trade_volume_24h_btc_normalized: 330.00229062521026,
  },
  {
    id: "bitpanda",
    name: "Bitpanda Pro",
    year_established: 2019,
    country: "Austria",
    description: "",
    url: "https://exchange.bitpanda.com",
    image:
      "https://assets.coingecko.com/markets/images/474/small/appicon-ios-pro.png?1622626638",
    has_trading_incentive: false,
    trust_score: 7,
    trust_score_rank: 81,
    trade_volume_24h_btc: 327.8444403463435,
    trade_volume_24h_btc_normalized: 327.8444403463435,
  },
  {
    id: "korbit",
    name: "Korbit",
    year_established: 2013,
    country: "South Korea",
    description: "",
    url: "https://www.korbit.co.kr/",
    image:
      "https://assets.coingecko.com/markets/images/28/small/korbit-logo.png?1584091827",
    has_trading_incentive: false,
    trust_score: 7,
    trust_score_rank: 82,
    trade_volume_24h_btc: 311.0057023074702,
    trade_volume_24h_btc_normalized: 311.0057023074702,
  },
  {
    id: "coinlist",
    name: "Coinlist",
    year_established: 2020,
    country: "United States",
    description:
      "CoinList is where early adopters invest and trade in high quality crypto assets before they land on other exchanges, including Filecoin, Celo, Solana, Nervos, Dfinity, Algorand, and many more.\r\n\r\nCoinList Trade is a fully-featured crypto spot exchange, built on battle-tested infrastructure and backed by some of the biggest names in the space. It will support the best new cryptoassets early in their lifecycles, as well as, most large cap established crypto. ",
    url: "https://pro.coinlist.co/",
    image:
      "https://assets.coingecko.com/markets/images/587/small/CoinList.png?1601540662",
    has_trading_incentive: false,
    trust_score: 7,
    trust_score_rank: 83,
    trade_volume_24h_btc: 259.1665250662446,
    trade_volume_24h_btc_normalized: 259.1665250662446,
  },
  {
    id: "zebpay",
    name: "ZebPay",
    year_established: 2014,
    country: "India",
    description:
      "ZebPay is a crypto-assets exchange with an established presence in India, Australia and Singapore. Since its inception in 2014 in India, ZebPay has rapidly expanded across geographies, and has been providing its services to crypto-traders and crypto-focused investors.\r\n\r\nThe choice of millions of traders, ZebPay offers its services across a wide range of devices, including mobile apps for those who are always on the go and a seamless web interface for users who prefer desktops.\r\n\r\nZebPay also offers an OTC desk, a bespoke service for users trading in large quantities of crypto assets. ZebPay OTC is a white-glove service available at every stage of the trading process - from the initial expert consultation all the way through to execution, with trade reporting and market insights.\r\n",
    url: "https://www.zebpay.com",
    image:
      "https://assets.coingecko.com/markets/images/151/small/Zebpay.jpg?1552892533",
    has_trading_incentive: false,
    trust_score: 7,
    trust_score_rank: 84,
    trade_volume_24h_btc: 250.1975260067923,
    trade_volume_24h_btc_normalized: 250.1975260067923,
  },
  {
    id: "mercado_bitcoin",
    name: "Mercado Bitcoin",
    year_established: 2016,
    country: "Brazil",
    description: "",
    url: "https://www.mercadobitcoin.com.br/",
    image:
      "https://assets.coingecko.com/markets/images/34/small/icon-256.png?1621420503",
    has_trading_incentive: false,
    trust_score: 7,
    trust_score_rank: 85,
    trade_volume_24h_btc: 149.79238679844997,
    trade_volume_24h_btc_normalized: 149.79238679844997,
  },
  {
    id: "narkasa",
    name: "Narkasa",
    year_established: 2020,
    country: "Turkey",
    description: "",
    url: "https://narkasa.com/",
    image:
      "https://assets.coingecko.com/markets/images/573/small/narkasa.jpg?1599029564",
    has_trading_incentive: false,
    trust_score: 7,
    trust_score_rank: 86,
    trade_volume_24h_btc: 37.74283235913668,
    trade_volume_24h_btc_normalized: 37.74283235913668,
  },
  {
    id: "nice_hash",
    name: "NiceHash",
    year_established: null,
    country: "Slovenia",
    description: "",
    url: "https://www.nicehash.com",
    image:
      "https://assets.coingecko.com/markets/images/546/small/logo_small_light.png?1637836622",
    has_trading_incentive: false,
    trust_score: 7,
    trust_score_rank: 87,
    trade_volume_24h_btc: 34.00139795390132,
    trade_volume_24h_btc_normalized: 34.00139795390132,
  },
  {
    id: "cybex",
    name: "Cybex DEX",
    year_established: 2017,
    country: null,
    description: null,
    url: "https://dex.cybex.io/",
    image:
      "https://assets.coingecko.com/markets/images/186/small/cybex.jpg?1529814811",
    has_trading_incentive: false,
    trust_score: 7,
    trust_score_rank: 88,
    trade_volume_24h_btc: 0.2285346861658843,
    trade_volume_24h_btc_normalized: 0.2285346861658843,
  },
  {
    id: "uniswap",
    name: "Uniswap (v3)",
    year_established: 2018,
    country: null,
    description: "",
    url: "https://app.uniswap.org/#/swap",
    image:
      "https://assets.coingecko.com/markets/images/665/small/uniswap-v3.png?1620241698",
    has_trading_incentive: false,
    trust_score: 6,
    trust_score_rank: 89,
    trade_volume_24h_btc: 36203.76343351599,
    trade_volume_24h_btc_normalized: 36203.76343351599,
  },
  {
    id: "bitcoin_com",
    name: "FMFW.io",
    year_established: 2019,
    country: "Bahamas",
    description:
      "The mission of FMFW.io is to empower people from all over the world to trade cryptocurrencies with ease and confidence, from first-time traders to advanced trading professionals. With high liquidity, 24/7 multilingual support and dozens of trading pairs, complemented with a high level of security, we offer an attractive platform for trading any cryptocurrency. Within one year since launch, on average, our exchange has been visited by more than 500K active traders per month, and this number continues to grow as you read this sentence. \r\n\r\nKey Features:\r\n\r\n- Enjoy more than 130 available trading pairs\r\n- Cutting-edge matching engine technologies\r\n- Up 5x and 10x leverage for more than 29 markets\r\n- Deep liquidity\r\n- User-friendly trading terminal\r\n- Tight spreads\r\n- Consistent trading competitions and giveaways",
    url: "https://fmfw.io/",
    image:
      "https://assets.coingecko.com/markets/images/467/small/fmfw.png?1635491491",
    has_trading_incentive: false,
    trust_score: 6,
    trust_score_rank: 90,
    trade_volume_24h_btc: 102642.24261796533,
    trade_volume_24h_btc_normalized: 23137.297546626152,
  },
  {
    id: "bingx",
    name: "BingX",
    year_established: null,
    country: null,
    description:
      "Founded in 2018, BingX is a crypto social trading exchange that offers spot, derivatives and copy trading services to more than 100 countries worldwide.\r\n\r\nBingX prides itself as the people's exchange by unlocking the fast-growing cryptocurrency market for everyone, connecting users with experts traders and a platform to invest in a simple, engaging and transparent way.",
    url: "https://bingx.com/en-us/",
    image:
      "https://assets.coingecko.com/markets/images/812/small/YtFwQwJr_400x400.jpg?1646056092",
    has_trading_incentive: false,
    trust_score: 6,
    trust_score_rank: 91,
    trade_volume_24h_btc: 15485.364261878573,
    trade_volume_24h_btc_normalized: 15485.364261878573,
  },
  {
    id: "pancakeswap_new",
    name: "PancakeSwap (v2)",
    year_established: 2020,
    country: null,
    description: "",
    url: "https://pancakeswap.finance",
    image:
      "https://assets.coingecko.com/markets/images/687/small/pancakeswap.jpeg?1626060212",
    has_trading_incentive: false,
    trust_score: 6,
    trust_score_rank: 92,
    trade_volume_24h_btc: 11218.958045145248,
    trade_volume_24h_btc_normalized: 11218.958045145248,
  },
  {
    id: "bithumb_global",
    name: "BitGlobal",
    year_established: 2019,
    country: "Seychelles",
    description: "",
    url: "https://www.bitglobal.com/",
    image:
      "https://assets.coingecko.com/markets/images/405/small/bitgloball.png?1639543042",
    has_trading_incentive: false,
    trust_score: 7,
    trust_score_rank: 93,
    trade_volume_24h_btc: 6844.293360039152,
    trade_volume_24h_btc_normalized: 6844.293360039152,
  },
  {
    id: "bitvavo",
    name: "Bitvavo",
    year_established: 2018,
    country: "Netherlands",
    description: "",
    url: "https://bitvavo.com/en",
    image:
      "https://assets.coingecko.com/markets/images/714/small/bitvavo-mark-square-black.png?1633688872",
    has_trading_incentive: false,
    trust_score: 6,
    trust_score_rank: 94,
    trade_volume_24h_btc: 5483.4983250790165,
    trade_volume_24h_btc_normalized: 5483.4983250790165,
  },
  {
    id: "uniswap_v2",
    name: "Uniswap (v2)",
    year_established: 2018,
    country: null,
    description: "",
    url: "https://app.uniswap.org/#/swap?use=V2",
    image:
      "https://assets.coingecko.com/markets/images/535/small/256x256_Black-1.png?1590893262",
    has_trading_incentive: false,
    trust_score: 6,
    trust_score_rank: 95,
    trade_volume_24h_btc: 4904.86852327751,
    trade_volume_24h_btc_normalized: 4904.86852327751,
  },
  {
    id: "astroport",
    name: "Astroport",
    year_established: null,
    country: null,
    description: "A meta AMM built on Terra. ",
    url: "https://app.astroport.fi/swap",
    image:
      "https://assets.coingecko.com/markets/images/822/small/EPpDQTZo_400x400.jpeg?1646185725",
    has_trading_incentive: false,
    trust_score: 6,
    trust_score_rank: 96,
    trade_volume_24h_btc: 4221.182488197077,
    trade_volume_24h_btc_normalized: 4221.182488197077,
  },
  {
    id: "sushiswap",
    name: "Sushiswap",
    year_established: 2020,
    country: null,
    description: "",
    url: "https://app.sushi.com/swap",
    image:
      "https://assets.coingecko.com/markets/images/576/small/2048x2048_Logo.png?1609208464",
    has_trading_incentive: false,
    trust_score: 6,
    trust_score_rank: 97,
    trade_volume_24h_btc: 3936.8567887085064,
    trade_volume_24h_btc_normalized: 3936.8567887085064,
  },
  {
    id: "traderjoe",
    name: "Trader Joe",
    year_established: null,
    country: null,
    description: "",
    url: "https://www.traderjoexyz.com/#/home",
    image:
      "https://assets.coingecko.com/markets/images/692/small/traderjoe.png?1628152581",
    has_trading_incentive: false,
    trust_score: 6,
    trust_score_rank: 98,
    trade_volume_24h_btc: 2852.0734165404947,
    trade_volume_24h_btc_normalized: 2852.0734165404947,
  },
  {
    id: "tokpie",
    name: "Tokpie",
    year_established: 2018,
    country: "Hong Kong",
    description: "",
    url: "https://tokpie.io/",
    image:
      "https://assets.coingecko.com/markets/images/436/small/logo_circle_100x100.png?1562226767",
    has_trading_incentive: false,
    trust_score: 6,
    trust_score_rank: 99,
    trade_volume_24h_btc: 2611.6793131501763,
    trade_volume_24h_btc_normalized: 2611.6793131501763,
  },
  {
    id: "quoine",
    name: "Liquid",
    year_established: 2014,
    country: "Japan",
    description: "",
    url: "https://liquid.com",
    image:
      "https://assets.coingecko.com/markets/images/40/small/liquid.png?1536133472",
    has_trading_incentive: false,
    trust_score: 6,
    trust_score_rank: 100,
    trade_volume_24h_btc: 2599.438211325027,
    trade_volume_24h_btc_normalized: 2599.438211325027,
  },
];
